---
- hosts: all
  user: www

  handlers:
    - import_tasks: handlers.yml
      static: yes

  tasks:
    - include_vars: vars.yml

    - name: Update the biostar-central
      shell: ls
      notify:
        - update git
        - server migrate
        - reload supervisor
        - restart nginx

    - name: Install pip requirements
      become: yes
      shell: "source /home/www/miniconda3/etc/profile.d/conda.sh && conda activate {{conda_env}} && pip install -r conf/pip_requirements.txt"
      args:
        executable: /bin/bash
        chdir: "{{ engine_dir }}"

    - name: Restart servers
      shell: ls
      notify:
        - reload supervisor
        - restart nginx
        - restart server

